# Generated by Django 4.0.8 on 2025-04-25 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Purchase Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='courses_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='Total price'),
        ),
    ]
