# Generated by Django 4.0.8 on 2025-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_photos/%Y/%m/%d/', verbose_name='Фото профиля'),
        ),
    ]
