# Generated by Django 4.0.8 on 2025-03-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tite',
            new_name='title',
        ),
    ]
