# Generated by Django 4.0.8 on 2025-04-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_price_alter_course_reviews_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
